import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useShallow } from 'zustand/shallow'

import { GameState, useGameStore } from '@/stores/gameStore'
import { useNarrativeStore } from '@/features/narrative'
import type { MomentOutcome, MomentoTrigger, NarrativeEvent } from '@/features/narrative'
import {
  applyMomentToElements,
  summarizeMomentImpact,
} from '@/features/competition'
import type {
  CompetitionResult,
  ElementOutcome,
  MomentImpact,
  ProgramScore,
  RankingEntry,
} from '@/types'
import { MomentOverlay, ScoreCard } from '@/components/ui'

// ─── timing constants (UI cadence) ───────────────────────────────────────────

const REVEAL_DELAY_MS = 700
const JUDGES_DELAY_MS = 1800
const SCORE_DELAY_MS  = 700
const INTRO_DELAY_MS  = 1200

type Stage =
  | 'sp_intro'
  | 'sp_skating'
  | 'sp_judges'
  | 'sp_score'
  | 'fp_intro'
  | 'fp_skating'
  | 'fp_judges'
  | 'fp_score'
  | 'classification'

// ─── component ────────────────────────────────────────────────────────────────

export function Competition() {
  const navigate = useNavigate()
  const { skater, season } = useGameStore(
    useShallow(s => ({ skater: s.currentSkater, season: s.currentSeason })),
  )
  const triggerMoment = useNarrativeStore(s => s.triggerMoment)
  const resolveChoice = useNarrativeStore(s => s.resolveChoice)

  // ── locate the most recent CompetitionResult for this skater ──────────────
  const initialResult = useMemo<CompetitionResult | null>(() => {
    if (!season || !skater) return null
    const owned = season.resultadosTemporada.filter(r => r.skaterId === skater.id)
    return owned[owned.length - 1] ?? null
  }, [season, skater])

  // ── working copies of the per-program data; mutated by Moments ────────────
  const [elementsCorto, setElementsCorto] = useState<ElementOutcome[] | null>(null)
  const [elementsLibre, setElementsLibre] = useState<ElementOutcome[] | null>(null)
  const [scoreCorto,    setScoreCorto]    = useState<ProgramScore | null>(null)
  const [scoreLibre,    setScoreLibre]    = useState<ProgramScore | null>(null)
  const [momentImpacts, setMomentImpacts] = useState<MomentImpact[]>([])
  const [classification, setClassification] = useState<RankingEntry[]>([])

  // initialise from the result generated by weekService
  useEffect(() => {
    if (!initialResult) return
    setElementsCorto(initialResult.programaCorto?.elements ? [...initialResult.programaCorto.elements] : null)
    setElementsLibre(initialResult.programaLibre?.elements ? [...initialResult.programaLibre.elements] : null)
    setScoreCorto(initialResult.programaCorto ?? null)
    setScoreLibre(initialResult.programaLibre ?? null)
    setMomentImpacts(initialResult.momentImpacts ? [...initialResult.momentImpacts] : [])
    setClassification(initialResult.clasificacion ? [...initialResult.clasificacion] : [])
  }, [initialResult])

  // ── stage machine ─────────────────────────────────────────────────────────
  const hasCorto = elementsCorto !== null
  const [stage, setStage] = useState<Stage>(hasCorto ? 'sp_intro' : 'fp_intro')
  const [revealedIndex, setRevealedIndex] = useState(0)
  const [moment, setMoment] = useState<NarrativeEvent | null>(null)
  const triggeredCorto = useRef<Set<MomentoTrigger>>(new Set())
  const triggeredLibre = useRef<Set<MomentoTrigger>>(new Set())
  const writtenBack    = useRef(false)

  // reset the stage machine + per-program trigger sets ONLY when a new
  // competition arrives. depending on `elementsCorto` here was a bug:
  // every Moment mutates that array, which would re-run this effect, snap the
  // stage back to sp_intro and clear the trigger set, causing infinite Moments.
  useEffect(() => {
    if (!initialResult) return
    setStage(initialResult.programaCorto ? 'sp_intro' : 'fp_intro')
    setRevealedIndex(0)
    triggeredCorto.current = new Set()
    triggeredLibre.current = new Set()
    writtenBack.current = false
  }, [initialResult])

  // ── intro auto-advances to skating ────────────────────────────────────────
  useEffect(() => {
    if (stage !== 'sp_intro' && stage !== 'fp_intro') return
    const id = window.setTimeout(() => {
      setStage(stage === 'sp_intro' ? 'sp_skating' : 'fp_skating')
      setRevealedIndex(0)
    }, INTRO_DELAY_MS)
    return () => window.clearTimeout(id)
  }, [stage])

  // active program selection for the skating stage
  const isSpSkating = stage === 'sp_skating'
  const isFpSkating = stage === 'fp_skating'
  const isSkating = isSpSkating || isFpSkating
  const activeElements = isSpSkating ? elementsCorto : elementsLibre
  const elementCount = activeElements?.length ?? 0
  const setActiveElements = isSpSkating ? setElementsCorto : setElementsLibre
  const triggeredFor = isSpSkating ? triggeredCorto : triggeredLibre

  // ── reveal-driver: ticks every REVEAL_DELAY_MS; checks for moments ────────
  useEffect(() => {
    if (!isSkating || moment || activeElements === null) return
    if (revealedIndex >= elementCount) {
      // skating done — fade to "judges deciding"
      const id = window.setTimeout(() => {
        setStage(isSpSkating ? 'sp_judges' : 'fp_judges')
      }, REVEAL_DELAY_MS)
      return () => window.clearTimeout(id)
    }
    const id = window.setTimeout(() => {
      const trigger = pickTriggerForIndex(revealedIndex, elementCount)
      if (trigger && !triggeredFor.current.has(trigger) && skater && season) {
        triggeredFor.current.add(trigger)
        const ev = triggerMoment(trigger, {
          skater, season,
          narrativeFlags:  useNarrativeStore.getState().narrativeFlags,
          emittedEvents:   useNarrativeStore.getState().emittedEvents,
          decisionHistory: useNarrativeStore.getState().decisionHistory,
        })
        if (ev) {
          setMoment(ev)
          return
        }
      }
      setRevealedIndex(i => i + 1)
    }, REVEAL_DELAY_MS)
    return () => window.clearTimeout(id)
  }, [isSkating, isSpSkating, moment, activeElements, elementCount, revealedIndex, skater, season, triggerMoment, triggeredFor])

  // ── judges → score animation transition ───────────────────────────────────
  useEffect(() => {
    if (stage !== 'sp_judges' && stage !== 'fp_judges') return
    const id = window.setTimeout(() => {
      // recompute the program score from the (possibly Moment-mutated) elements;
      // PCS is unaffected by Moments so we keep the value computed by weekService.
      const isSp = stage === 'sp_judges'
      const elements = isSp ? elementsCorto : elementsLibre
      const baseScore = isSp ? scoreCorto : scoreLibre
      if (elements && baseScore) {
        const finalScore = recomputeProgramScoreKeepingPcs(elements, baseScore)
        if (isSp) setScoreCorto(finalScore)
        else      setScoreLibre(finalScore)
      }
      setStage(isSp ? 'sp_score' : 'fp_score')
    }, JUDGES_DELAY_MS)
    return () => window.clearTimeout(id)
  }, [stage, elementsCorto, elementsLibre, scoreCorto, scoreLibre])

  // ── score → next intro / final classification ─────────────────────────────
  useEffect(() => {
    if (stage !== 'sp_score' && stage !== 'fp_score') return
    const id = window.setTimeout(() => {
      if (stage === 'sp_score') {
        setStage('fp_intro')
      } else {
        // recompute classification with the player's possibly-updated totals
        if (initialResult) {
          const playerCortoTotal = scoreCorto?.total ?? 0
          const playerLibreTotal = scoreLibre?.total ?? 0
          const playerTotal = playerCortoTotal + playerLibreTotal
          const others = (initialResult.clasificacion ?? []).filter(c => !c.esJugador)
          const merged: RankingEntry[] = [
            ...others,
            {
              posicion:      0,  // re-numbered below
              participantId: skater!.id,
              nombre:        skater!.name,
              nacionalidad:  skater!.nationality,
              totalCombinado: playerTotal,
              scoreCorto:     playerCortoTotal,
              scoreLibre:     playerLibreTotal,
              esJugador:      true,
            },
          ]
          merged.sort((a, b) => b.totalCombinado - a.totalCombinado)
          setClassification(merged.map((e, i) => ({ ...e, posicion: i + 1 })))
        }
        setStage('classification')
      }
    }, SCORE_DELAY_MS * 4)
    return () => window.clearTimeout(id)
  }, [stage, initialResult, skater, scoreCorto, scoreLibre])

  // ── moment resolution: mutate the active elements before reveal continues ─
  function handleMomentChoice(optionId: string) {
    if (!moment || !skater || !season) return
    const programType = isSpSkating ? 'corto' : 'libre'
    const outcome = resolveChoice(optionId)
    setMoment(null)
    if (!outcome || !('goeBonusCurrent' in outcome)) {
      setRevealedIndex(i => i + 1)
      return
    }
    const mo = outcome as MomentOutcome
    const elements = activeElements
    if (!elements) {
      setRevealedIndex(i => i + 1)
      return
    }
    const before = [...elements]
    const next = applyMomentToElements(elements, mo, revealedIndex, mo.causesFall)
    setActiveElements(next)
    setMomentImpacts(prev => [
      ...prev,
      summarizeMomentImpact(before, next, programType, moment.id, optionId, mo.causesFall),
    ])
    if (mo.bondDelta !== 0) {
      const gs = useGameStore.getState()
      if (gs.currentSkater) {
        gs.applyWeekTransition({
          skater: {
            weeklyState: {
              ...gs.currentSkater.weeklyState,
              vinculo: clamp(gs.currentSkater.weeklyState.vinculo + mo.bondDelta),
            },
          },
        })
      }
    }
    setRevealedIndex(i => i + 1)
  }

  // ── continue → write-back updated CompetitionResult and navigate ──────────
  function handleContinue() {
    if (writtenBack.current) return
    writtenBack.current = true
    const gs = useGameStore.getState()
    const seasonRef = gs.currentSeason
    if (initialResult && seasonRef) {
      const playerEntry = classification.find(c => c.esJugador)
      const tesCombinado = (scoreCorto?.tes ?? 0) + (scoreLibre?.tes ?? 0)
      const pcsCombinado = (scoreCorto?.pcs ?? 0) + (scoreLibre?.pcs ?? 0)
      const caidasCombinadas = (scoreCorto?.caidas ?? 0) + (scoreLibre?.caidas ?? 0)
      const deduccionesCombinadas = (scoreCorto?.deducciones ?? 0) + (scoreLibre?.deducciones ?? 0)
      const totalCombinado = tesCombinado + pcsCombinado - deduccionesCombinadas
      const updated: CompetitionResult = {
        ...initialResult,
        tes:           tesCombinado,
        pcs:           pcsCombinado,
        total:         totalCombinado,
        caidas:        caidasCombinadas,
        deducciones:   deduccionesCombinadas,
        posicion:      playerEntry?.posicion ?? initialResult.posicion,
        programaCorto: scoreCorto,
        programaLibre: scoreLibre,
        clasificacion: classification,
        momentImpacts,
      }
      const list = seasonRef.resultadosTemporada.map(r =>
        r.id === updated.id ? updated : r,
      )
      gs.applyWeekTransition({ season: { resultadosTemporada: list } })
    }
    if (seasonRef && seasonRef.historialSemanas.length >= 30) {
      gs.changeState(GameState.SEASON_END)
      navigate('/fin-temporada', { replace: true })
      return
    }
    gs.changeState(GameState.WEEKLY_PLANNING)
    navigate('/semana', { replace: true })
  }

  if (!skater || !season || !initialResult) {
    return (
      <div className="flex min-h-screen items-center justify-center glace-vignette">
        <p className="font-display italic text-content-secondary">No hay competición lista.</p>
      </div>
    )
  }

  // ── derived view-state ────────────────────────────────────────────────────
  const showRink = isSkating
  const showJudges = stage === 'sp_judges' || stage === 'fp_judges'
  const showScore = stage === 'sp_score' || stage === 'fp_score'
  const showClassification = stage === 'classification'

  return (
    <div className="relative flex min-h-screen flex-col bg-bg-deep glace-grain">
      {/* HEADER */}
      <header className="relative z-10 mx-auto grid w-full max-w-7xl grid-cols-12 items-end gap-6 px-10 pt-10 pb-6">
        <div className="col-span-12 flex items-baseline gap-4">
          <span className="glace-eyebrow text-gold">— competición</span>
          <span className="glace-hairline flex-1" />
          <span className="glace-eyebrow text-content-disabled">
            semana {String(season.semanaActual).padStart(2, '0')} · {initialResult.tipo}
          </span>
        </div>
        <div className="col-span-12 md:col-span-9 flex flex-col gap-1">
          <h1 className="glace-reveal-letter font-display text-7xl leading-[0.9] text-content-primary">
            {initialResult.nombreCompeticion}
          </h1>
          <p className="font-display italic text-lg text-content-secondary">
            {programLabel(stage)} · {skater.name}
          </p>
        </div>
      </header>

      {/* MAIN */}
      <main className="relative z-10 mx-auto grid w-full max-w-7xl flex-1 grid-cols-12 gap-x-8 gap-y-6 px-10 pb-32">
        {(stage === 'sp_intro' || stage === 'fp_intro') && (
          <ProgramIntro stage={stage} skaterName={skater.name} />
        )}

        {showRink && activeElements && (
          <>
            <section className="col-span-12 md:col-span-8 flex flex-col">
              <RinkView progress={revealedIndex / Math.max(1, elementCount)} muted={moment !== null} />
            </section>
            <section className="col-span-12 md:col-span-4 flex flex-col gap-3 border-l border-border-subtle pl-6">
              <span className="glace-eyebrow">— ejecución</span>
              <ol className="flex flex-col gap-px bg-border-subtle">
                {activeElements.map((eo, i) => (
                  <li key={i}>
                    <ElementCard outcome={eo} revealed={i < revealedIndex} index={i} />
                  </li>
                ))}
              </ol>
            </section>
          </>
        )}

        {showJudges && <JudgesWaiting />}

        {showScore && (
          <ScoreReveal
            score={stage === 'sp_score' ? scoreCorto : scoreLibre}
            programLabel={stage === 'sp_score' ? 'programa corto' : 'programa libre'}
          />
        )}

        {showClassification && (
          <ClassificationView
            classification={classification}
            momentImpacts={momentImpacts}
          />
        )}
      </main>

      {/* FOOTER — only shown at the very end so the player can advance */}
      {showClassification && (
        <footer className="relative z-10 border-t border-border-subtle bg-bg-deep">
          <div className="mx-auto grid max-w-7xl grid-cols-12 items-baseline gap-x-8 gap-y-6 px-10 py-6">
            <p className="col-span-9 font-display italic text-lg text-content-secondary">
              {flavorComment(scoreCorto, scoreLibre, classification)}
            </p>
            <button
              type="button"
              onClick={handleContinue}
              className="group col-span-3 flex items-baseline justify-end gap-3"
            >
              <span className="glace-eyebrow text-ice-300 group-hover:text-ice-200 transition-colors">
                continuar
              </span>
              <span className="font-display text-3xl text-content-primary group-hover:text-ice-200 transition-colors">
                <span className="ml-2 inline-block transition-transform duration-300 group-hover:translate-x-2">→</span>
              </span>
            </button>
          </div>
        </footer>
      )}

      {moment && <MomentOverlay event={moment} onChoose={handleMomentChoice} />}
    </div>
  )
}

// ─── helpers ─────────────────────────────────────────────────────────────────

const clamp = (v: number, lo = 0, hi = 100) => Math.max(lo, Math.min(hi, v))

/**
 * recomputes a ProgramScore from possibly-mutated elements, preserving the
 * PCS that the engine produced. Moments only touch TES — PCS depends on
 * judges + skater + program, none of which the player can change in-flight.
 */
function recomputeProgramScoreKeepingPcs(
  elements: ElementOutcome[],
  baseScore: ProgramScore,
): ProgramScore {
  let tes = 0
  let caidas = 0
  let deducciones = 0
  for (const e of elements) {
    tes += e.tesBruto
    if (e.caida) caidas += 1
    deducciones += e.deduccion
  }
  return {
    ...baseScore,
    elements: [...elements],
    tes,
    caidas,
    deducciones,
    total: tes + baseScore.pcs - deducciones,
  }
}

function pickTriggerForIndex(index: number, total: number): MomentoTrigger | null {
  if (total === 0) return null
  if (index === 0) return 'early'
  if (index === Math.floor(total / 2)) return 'mid'
  if (index === Math.max(0, total - 2)) return 'late'
  return null
}

function programLabel(stage: Stage): string {
  if (stage === 'sp_intro' || stage === 'sp_skating' || stage === 'sp_judges' || stage === 'sp_score') {
    return 'programa corto'
  }
  if (stage === 'fp_intro' || stage === 'fp_skating' || stage === 'fp_judges' || stage === 'fp_score') {
    return 'programa libre'
  }
  return 'clasificación final'
}

function flavorComment(
  sp: ProgramScore | null,
  fp: ProgramScore | null,
  cls: RankingEntry[],
): string {
  const player = cls.find(c => c.esJugador)
  const total = (sp?.total ?? 0) + (fp?.total ?? 0)
  if (player?.posicion === 1) return 'oro. nadie pudo seguirte hoy en el hielo.'
  if (player && player.posicion <= 3) return `subes al podio en ${player.posicion}º. el aplauso lo merece.`
  if (total > 200) return 'una actuación que dejó marca. se nota el oficio.'
  if ((sp?.caidas ?? 0) + (fp?.caidas ?? 0) > 1) return 'irregular: el público notó que algo no fluyó.'
  if (total > 150) return 'una actuación sólida: lo construido en la pista paga.'
  return 'hay materia para revisar al volver al hielo.'
}

// ─── child views ─────────────────────────────────────────────────────────────

function ProgramIntro({ stage, skaterName }: { stage: Stage; skaterName: string }) {
  const isSp = stage === 'sp_intro'
  return (
    <section className="col-span-12 flex flex-col items-center justify-center gap-8 py-20 text-center">
      <span className="glace-eyebrow text-gold">
        {isSp ? '— primer programa' : '— segundo programa'}
      </span>
      <h2 className="glace-reveal-letter font-display text-6xl text-content-primary">
        {isSp ? 'Programa corto' : 'Programa libre'}
      </h2>
      <div className="glace-hairline w-32" />
      <p className="font-display italic text-2xl text-content-secondary max-w-2xl">
        {isSp
          ? `${skaterName} se prepara para entrar a la pista.`
          : `${skaterName} vuelve al hielo. Esta es la prueba larga.`}
      </p>
    </section>
  )
}

function JudgesWaiting() {
  return (
    <section className="col-span-12 flex flex-col items-center justify-center gap-6 py-20 text-center"
      style={{ backgroundColor: 'rgba(12, 18, 32, 0.85)' }}>
      <span className="glace-eyebrow text-content-disabled">— el panel delibera</span>
      <p className="glace-reveal-fade font-display italic text-3xl text-content-secondary max-w-2xl">
        Esperando puntuación de los jueces…
      </p>
      <div className="flex gap-2">
        <span className="h-1 w-1 rounded-full bg-ice-400 animate-pulse" />
        <span className="h-1 w-1 rounded-full bg-ice-400 animate-pulse" style={{ animationDelay: '180ms' }} />
        <span className="h-1 w-1 rounded-full bg-ice-400 animate-pulse" style={{ animationDelay: '360ms' }} />
      </div>
    </section>
  )
}

function ScoreReveal({ score, programLabel }: { score: ProgramScore | null; programLabel: string }) {
  if (!score) return null
  return (
    <section className="col-span-12 flex flex-col items-center justify-center gap-10 py-12">
      <div className="flex flex-col items-center gap-2">
        <span className="glace-eyebrow text-gold">— puntuación oficial —</span>
        <h2 className="font-display text-3xl text-content-primary capitalize">{programLabel}</h2>
      </div>

      <div className="grid w-full max-w-5xl grid-cols-12 items-end gap-6">
        <div className="col-span-3 glace-reveal-fade">
          <ScoreCard label="tes" value={score.tes} narrative accent="ice" size="lg" />
        </div>
        <div className="col-span-3 glace-reveal-fade glace-stagger-1">
          <ScoreCard label="pcs" value={score.pcs} narrative accent="frost" size="lg" />
        </div>
        <div className="col-span-3 glace-reveal-fade glace-stagger-2">
          <ScoreCard label="deducciones" value={score.deducciones} narrative accent="neutral" size="md" />
        </div>
        <div className="col-span-3 glace-reveal-fade glace-stagger-3">
          <ScoreCard label="total" value={score.total} narrative accent="gold" size="xl" />
        </div>
      </div>

      <div className="mx-auto grid w-full max-w-3xl grid-cols-5 gap-3 border-t border-border-subtle pt-6">
        {(['sk', 'tr', 'pe', 'co', 'in'] as const).map(k => (
          <div key={k} className="flex flex-col items-center gap-1">
            <span className="glace-eyebrow text-content-disabled">{k}</span>
            <span className="font-display text-2xl text-content-secondary tabular-nums">
              {score.pcsDetalle[k].toFixed(2)}
            </span>
          </div>
        ))}
      </div>
    </section>
  )
}

function ClassificationView({
  classification, momentImpacts,
}: { classification: RankingEntry[]; momentImpacts: MomentImpact[] }) {
  return (
    <section className="col-span-12 flex flex-col gap-8">
      <header className="flex items-baseline gap-4">
        <span className="glace-eyebrow text-gold">— clasificación final</span>
        <span className="glace-hairline flex-1" />
      </header>
      <div className="flex flex-col gap-px bg-border-subtle max-h-[60vh] overflow-y-auto">
        {classification.map(entry => (
          <ClassificationRow key={entry.participantId} entry={entry} />
        ))}
      </div>
      {momentImpacts.length > 0 && (
        <aside className="border-t border-border-subtle pt-6">
          <span className="glace-eyebrow text-semantic-human">— momentos del programa</span>
          <ul className="mt-3 flex flex-col gap-2">
            {momentImpacts.map((m, i) => (
              <li key={i} className="font-display italic text-content-secondary">
                <span className="capitalize text-content-muted">{m.programType}:</span> {m.descripcion}
              </li>
            ))}
          </ul>
        </aside>
      )}
    </section>
  )
}

function ClassificationRow({ entry }: { entry: RankingEntry }) {
  const isPodium = entry.posicion <= 3
  const tone = entry.esJugador
    ? 'bg-bg-raised text-content-primary'
    : 'bg-bg-deep text-content-secondary'
  const accent = entry.esJugador
    ? 'text-gold'
    : isPodium ? 'text-frost-400' : 'text-content-muted'
  return (
    <div className={['grid grid-cols-12 items-baseline gap-4 px-4 py-3', tone].join(' ')}>
      <span className={['col-span-1 font-display tabular-nums text-2xl leading-none', accent].join(' ')}>
        {String(entry.posicion).padStart(2, '0')}
      </span>
      <span className="col-span-1 font-sans text-xs uppercase tracking-widest text-content-muted">
        {entry.nacionalidad}
      </span>
      <span className="col-span-5 font-display text-lg">
        {entry.nombre}
        {entry.esJugador && <span className="ml-2 glace-eyebrow text-gold">— tú</span>}
      </span>
      <span className="col-span-2 font-sans tabular-nums text-sm text-content-muted text-right">
        sp {entry.scoreCorto !== null ? entry.scoreCorto.toFixed(2) : '—'}
      </span>
      <span className="col-span-2 font-sans tabular-nums text-sm text-content-muted text-right">
        fs {entry.scoreLibre.toFixed(2)}
      </span>
      <span className="col-span-1 font-display tabular-nums text-xl text-content-primary text-right">
        {entry.totalCombinado.toFixed(2)}
      </span>
    </div>
  )
}

function RinkView({ progress, muted }: { progress: number; muted: boolean }) {
  const pct = Math.max(0, Math.min(1, progress))
  const theta = pct * Math.PI * 2
  const cx = 50 + 38 * Math.cos(theta)
  const cy = 50 + 22 * Math.sin(theta)

  const trail = Array.from({ length: 8 }, (_, k) => {
    const t = theta - (k + 1) * 0.08
    return {
      x: 50 + 38 * Math.cos(t),
      y: 50 + 22 * Math.sin(t),
      o: 0.6 - k * 0.07,
    }
  })

  return (
    <div className={[
      'flex aspect-[2/1] items-center justify-center transition-opacity duration-500',
      muted ? 'opacity-40' : 'opacity-100',
    ].join(' ')}>
      <svg viewBox="0 0 100 50" className="h-full w-full">
        <defs>
          <radialGradient id="rink-glow" cx="50%" cy="50%">
            <stop offset="0%"   stopColor="rgba(78,159,200,0.10)" />
            <stop offset="100%" stopColor="rgba(78,159,200,0)" />
          </radialGradient>
        </defs>
        <rect x="0" y="0" width="100" height="50" fill="url(#rink-glow)" />
        <ellipse cx={50} cy={25} rx={42} ry={20} fill="none" stroke="var(--c-border)" strokeWidth={0.25} />
        <ellipse cx={50} cy={25} rx={38} ry={11} fill="none" stroke="var(--c-ice-600)" strokeOpacity={0.4} strokeWidth={0.2} strokeDasharray="0.8 1.4" />
        {trail.map((p, i) => (
          <circle
            key={i}
            cx={p.x} cy={p.y / 2 + 12.5}
            r={1.0 - i * 0.1}
            fill="var(--c-ice-400)"
            opacity={p.o}
          />
        ))}
        <circle cx={cx} cy={cy / 2 + 12.5} r={1.4} fill="var(--c-ice-300)">
          <animate attributeName="r" values="1.2;1.8;1.2" dur="1.6s" repeatCount="indefinite" />
        </circle>
      </svg>
    </div>
  )
}

function ElementCard({
  outcome, revealed, index,
}: { outcome: ElementOutcome; revealed: boolean; index: number }) {
  const el = outcome.element
  const goeColor = outcome.caida
    ? 'text-danger'
    : outcome.goe >= 1.5
      ? 'text-frost-400'
      : outcome.goe <= -0.5
        ? 'text-content-muted'
        : 'text-ice-300'
  return (
    <div
      className={[
        'flex items-baseline justify-between gap-4 bg-bg-deep px-3 py-3 transition-opacity duration-500',
        revealed ? 'opacity-100' : 'opacity-30',
      ].join(' ')}
    >
      <span className="font-display tabular-nums text-2xl text-content-disabled leading-none w-7">
        {String(index + 1).padStart(2, '0')}
      </span>
      <div className="flex-1">
        <p className="font-display text-base text-content-primary leading-tight">
          {el.tipo === 'salto'
            ? `${el.rotaciones}T ${el.tipoSalto}`
            : el.tipo}
          {el.esCombinacion && (
            <span className="ml-2 text-xs uppercase tracking-widest text-ice-300">combo</span>
          )}
          {revealed && outcome.caida && (
            <span className="ml-2 text-xs uppercase tracking-widest text-danger">caída</span>
          )}
          {revealed && outcome.invalid && (
            <span className="ml-2 text-xs uppercase tracking-widest text-danger">no value</span>
          )}
        </p>
      </div>
      <span className="font-display tabular-nums text-sm text-content-muted leading-none">
        {el.dificultadBase.toFixed(1)}
      </span>
      <span className={[
        'font-display tabular-nums text-sm leading-none w-14 text-right transition-opacity duration-500',
        revealed ? 'opacity-100' : 'opacity-0',
        goeColor,
      ].join(' ')}>
        {revealed ? formatGOE(outcome.goe) : '—'}
      </span>
    </div>
  )
}

function formatGOE(goe: number): string {
  const sign = goe >= 0 ? '+' : ''
  return `${sign}${goe.toFixed(1)}`
}
